### ISSUE TITLE
すべてホワイトリストで管理する

### ISSUE THREAD

**Issue by yuma140902** [yuma140902/dotfiles-rs#6]
すべてホワイトリストで管理することにする

**Comment by yuma140902** [comment]
close #5

**Comment by yuma140902** [comment]
dotfiles-rs.ymlは
```yml
files:
- .gitconfig
- .vimrc
- .config/someconfig.json
- .config/nested/config.toml

dirs:
- .vim
- .config/nvim
```
のような感じ
